server:
    port: 8088
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
    application:
        name: be-instagram-clone
    #maria db
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWD}
        driver-class-name: ${DB_DRIVER}
    #h2 db

    #  datasource:
    #    driver-class-name: org.h2.Driver
    #    #url: jdbc:h2:mem:inspire
    #    url: jdbc:h2:file:./data/inspire;AUTO_SERVER=TRUE
    #    username: root
    #    passwd:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MariaDBDialect
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: ${FACEBOOK_APP_ID} #너의-페이스북-앱-ID-여기-입력
                        client-secret: ${FACEBOOK_SECRET_CODE} #너의-페이스북-앱-시크릿-여기-입력

jwt:
    secret: ${JWT_SECRET_KEY}

file:
    upload-dir: C:/uploads
